# Generated by Django 3.0.7 on 2023-03-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('router', 'Firewall'), ('router', 'Router'), ('switch', 'Switch'), ('loadbalancer', 'Loadbalancer')], max_length=15)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('installing', 'Installing'), ('done', 'Done'), ('failed', 'Failed'), ('success', 'Success')], default='waiting', max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('active', models.BooleanField()),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', related_query_name='device', to='data.Device')),
            ],
        ),
    ]
